### ISSUE TITLE
Only works with ESM loading

### ISSUE THREAD

**Issue by grybykm** [alienfast/vite-plugin-tsconfig#3]
The error I'm getting is: 
```
Failed to resolve "vite-plugin-tsconfig". This package is ESM only but it was tried to load by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]
```

I haven't tried using it with vite version below 5.

**Comment by husayt** [comment]
@rosskevin is this module supporting vite 5?

Thanks

**Comment by rosskevin** [comment]
@husayt I haven't tried with vite 5, but the message you are getting is because this is an ESM package and you are trying to load it with require.  Instructing on how to use ESM in your project is beyond the scope of this project, but you'll need to trigger ESM loading with something like `module: root` in your `package.json` or perhaps use `.mjs`  for your config file extension.
